### ISSUE TITLE
Design Thumbnail for "Dog" Learning Unit

### ISSUE THREAD

**Issue by stapps21** [schule4-0/pets#18]
## Description:

We need to create thumbnails for the learning units. For now, let's start with designing a thumbnail for the "Dog" learning unit.

## Tasks:

- [ ] Design a thumbnail for the "Dog" learning unit
- [ ] Seek feedback from team members and iterate if necessary
- [ ] Replace current placeholder thumbnail
